// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;
using server.Datas;

namespace server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220310105335_Ingredients")]
    partial class Ingredients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 3, 3, 5, 25, 4, 0, DateTimeKind.Unspecified),
                            Name = "Barbecue"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 4, 6, 15, 14, 0, DateTimeKind.Unspecified),
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 4, 6, 3, 17, 25, 0, DateTimeKind.Unspecified),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 5, 6, 2, 2, 2, 0, DateTimeKind.Unspecified),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2018, 5, 7, 1, 15, 15, 0, DateTimeKind.Unspecified),
                            Name = "Dinner"
                        });
                });

            modelBuilder.Entity("server.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oil",
                            Price = 3f,
                            Quantity = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flour",
                            Price = 30f,
                            Quantity = 25,
                            Unit = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sugar",
                            Price = 3f,
                            Quantity = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salt",
                            Price = 2f,
                            Quantity = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Olive Oil",
                            Price = 20f,
                            Quantity = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Egg",
                            Price = 9f,
                            Quantity = 30,
                            Unit = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chicken meat",
                            Price = 10f,
                            Quantity = 1,
                            Unit = 2
                        });
                });

            modelBuilder.Entity("server.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 17, 190, 142, 41, 72, 227, 31, 133, 172, 222, 148, 79, 134, 175, 224, 100, 214, 144, 129, 101, 238, 123, 55, 104, 54, 239, 2, 110, 82, 200, 28, 79, 239, 199, 36, 2, 83, 209, 235, 25, 193, 140, 127, 212, 212, 17, 178, 182, 190, 14, 74, 106, 64, 161, 196, 243, 181, 71, 150, 245, 245, 111, 102, 153 },
                            PasswordSalt = new byte[] { 124, 37, 72, 16, 46, 113, 33, 119, 2, 5, 214, 238, 27, 59, 104, 177, 167, 137, 195, 149, 226, 28, 26, 136, 199, 151, 4, 182, 55, 250, 149, 9, 163, 222, 224, 95, 67, 11, 198, 96, 73, 126, 179, 53, 182, 0, 25, 140, 44, 202, 89, 182, 3, 164, 12, 75, 230, 173, 227, 3, 212, 19, 42, 124, 84, 102, 240, 143, 21, 219, 169, 112, 23, 245, 56, 53, 61, 253, 75, 136, 79, 64, 231, 97, 65, 67, 138, 166, 192, 134, 174, 32, 185, 213, 179, 165, 214, 27, 84, 122, 163, 124, 144, 198, 190, 156, 232, 187, 159, 126, 89, 221, 195, 26, 210, 86, 84, 167, 153, 31, 36, 178, 55, 42, 255, 122, 201, 22 },
                            Username = "user123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
